### ISSUE TITLE
rtl guide

### ISSUE THREAD

**Issue by hamidreza411** [Husseinhj/rtlstackedit#1]
change the '' Usage'' to '' How to Use''
1- To use the RTL version, first Open [rtlStackedit](https://husseinhj.github.io/rtlstackedit/#) website
2- then Go to ''More'' option in the side bar by clicking stackedit's icon on the upper right
3- Open the ''settings'' page
4- Add the following to ''Custom settings'' section:
```
editor:
  previewDirection: 'rtl'
```
5- finally Refresh the page and Enjoy

**Comment by Husseinhj** [comment]
@hamidreza411 Check the new version 👍
